# Generated by Django 4.2.23 on 2025-07-11 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalFlowTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ApprovalFlowStepTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_number", models.IntegerField()),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("PI", "PI Review"),
                            ("ETHICS", "Ethics Review"),
                            ("ADMIN", "Admin Review"),
                            ("DUAL", "Dual Approval"),
                            ("AI", "AI Suggestion"),
                            ("ARBITER", "Arbiter"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "is_parallel",
                    models.BooleanField(
                        default=False,
                        help_text="Is this a parallel step (e.g., dual approval)?",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        help_text="Condition expression, e.g., high_sensitivity",
                        max_length=255,
                    ),
                ),
                (
                    "flow_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="approvals.approvalflowtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["flow_template", "step_number"],
                "unique_together": {("flow_template", "step_number", "node_type")},
            },
        ),
    ]
