# Generated by Django 4.2.23 on 2025-07-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0002_approvalflowtemplate_approvalflowsteptemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalrequest",
            name="sensitivity",
            field=models.CharField(
                choices=[("normal", "Normal"), ("high", "High Sensitivity")],
                default="normal",
                max_length=20,
            ),
        ),
    ]
